// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAiuTts4lJZiLHIBB-aBeCmcCoxdNkU6TE',
//     appId: '1:568982823809:web:8a0fece91dc32b81ec7e80',
//     messagingSenderId: '568982823809',
//     projectId: 'rotta-mobile',
//     authDomain: 'rotta-mobile.firebaseapp.com',
//     storageBucket: 'rotta-mobile.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDVL-NtCqg9rYlG-O1IuTpib4P0FTQZH88',
//     appId: '1:568982823809:android:4e8a3d10b3f11138ec7e80',
//     messagingSenderId: '568982823809',
//     projectId: 'rotta-mobile',
//     storageBucket: 'rotta-mobile.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyB74N9Lfvloi2MkNTF8l8l_I5Eu8coAg_c',
//     appId: '1:568982823809:ios:852ec81188506e19ec7e80',
//     messagingSenderId: '568982823809',
//     projectId: 'rotta-mobile',
//     storageBucket: 'rotta-mobile.appspot.com',
//     iosBundleId: 'com.example.rottamobile',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyB74N9Lfvloi2MkNTF8l8l_I5Eu8coAg_c',
//     appId: '1:568982823809:ios:852ec81188506e19ec7e80',
//     messagingSenderId: '568982823809',
//     projectId: 'rotta-mobile',
//     storageBucket: 'rotta-mobile.appspot.com',
//     iosBundleId: 'com.example.rottamobile',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAiuTts4lJZiLHIBB-aBeCmcCoxdNkU6TE',
//     appId: '1:568982823809:web:825180a20394f78fec7e80',
//     messagingSenderId: '568982823809',
//     projectId: 'rotta-mobile',
//     authDomain: 'rotta-mobile.firebaseapp.com',
//     storageBucket: 'rotta-mobile.appspot.com',
//   );
// }
